server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
      register-with-eureka: true

kafka:
  topic:
    order: orders
    payment: payments
    inventory: inventories