 spring:
  application:
    name: eCommerce-apiGateway
  cloud:
    gateway:
      routes:
        - id: AuthenticationService
          uri: lb://AuthenticationService
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter

        - id: ProductService
          uri: lb://ProductService
          predicates:
            - Path=/product/**
          filters:
            - AuthenticationFilter

        - id: ProductService
          uri: lb://ProductService
          predicates:
            - Path=/category/**
          filters:
            - AuthenticationFilter
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
    register-with-eureka: true


