spring:
  application:
    name: eCommerce-apiGateway
  cloud:
    gateway:

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
    register-with-eureka: true


